version: '2'
services:
    keycloak:
        build: .
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB_URL=jdbc:mysql://dossierfacile-keycloak-preprod.ctbawdqzszza.eu-west-3.rds.amazonaws.com/keycloak
            - KC_DB_DATABASE=keycloak
            - KC_DB_PASSWORD=hMXqHGYpoapCxzYU8i3O
            - KC_DB_USERNAME=admin
            - KC_DB=mysql
            - KC_HTTP_RELATIVE_PATH=/auth
        ports:
            - "8085:8080"
