services:
  postgres:
    image: postgres:12
    container_name: keycloak_postgres_db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: your_very_secure_password
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432" # Exposed on port 5433 on localhost
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_network

  keycloak:
    build: .
    container_name: keycloak_dossierfacile
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=your_very_secure_password
      - KC_HOSTNAME=localhost
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=your_very_secure_password
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  keycloak_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge